fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "test@hetg.net"
        sender_name: "test@hetg.net"
    service:
        mailer: 'fos_user.mailer.noop'